import type { Metadata, Viewport } from 'next';
import { Archivo, Instrument_Serif, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import './home.css';
import './pages.css';
import './overlays.css';
import { JsonLd } from '@/components/JsonLd';
import { Masthead } from '@/components/Masthead';
import { SiteFoot } from '@/components/SiteFoot';
import { QuotePopupLoader } from '@/components/QuotePopupLoader';
import { ScrollEffects } from '@/components/ScrollEffects';
import { WhatsAppWidget } from '@/components/WhatsAppWidget';
import { company, socials } from '@/lib/site-data';
import { absoluteUrl, ORGANIZATION_ID, SITE_LOCALE, SITE_NAME, SITE_URL, WEBSITE_ID } from '@/lib/seo';

// One Archivo instance serves both display and body text. Only Archivo is preloaded: it renders the headline
// (the LCP text). The accent serif and mono labels load right after without delaying first paint.
const sans = Archivo({ subsets: ['latin'], display: 'swap', variable: '--font-display' });
const accent = Instrument_Serif({ subsets: ['latin'], weight: '400', style: 'italic', display: 'swap', variable: '--font-accent', preload: false });
const mono = JetBrains_Mono({ subsets: ['latin'], display: 'swap', variable: '--font-mono', preload: false });

// Pages set their own title, description, canonical and Open Graph tags through `pageMetadata` in lib/seo.ts.
// Nothing page-specific (such as a canonical) lives here, so no route can inherit the homepage's values.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'CanzoTech — Software Engineering Studio',
    template: `%s — ${SITE_NAME}`,
  },
  description: company.description,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  formatDetection: { telephone: false, email: false, address: false },
  openGraph: { type: 'website', siteName: SITE_NAME, locale: SITE_LOCALE },
  twitter: { card: 'summary_large_image' },
  // Indexable by default; utility pages (404, thank-you, legal) override this with noindex.
  robots: { index: true, follow: true, 'max-image-preview': 'large' },
  // Static files in public/ (generated by scripts/generate-icons.mjs). Google reads the homepage's icon.
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '48x48' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon-48x48.png', sizes: '48x48', type: 'image/png' },
      { url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
      { url: '/icon-192x192.png', sizes: '192x192', type: 'image/png' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }],
  },
  manifest: '/site.webmanifest',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#ffffff',
  colorScheme: 'light',
};

const LOGO_URL = absoluteUrl('/images/brand/canzotech-logo.webp');

const organizationSchema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      // ProfessionalService is a LocalBusiness subtype, so the office address and phone qualify for local results.
      '@type': ['Organization', 'ProfessionalService'],
      '@id': ORGANIZATION_ID,
      name: company.name,
      url: SITE_URL,
      logo: { '@type': 'ImageObject', url: LOGO_URL, width: 500, height: 500 },
      image: LOGO_URL,
      description: company.description,
      email: company.email,
      telephone: company.phoneE164,
      address: {
        '@type': 'PostalAddress',
        streetAddress: company.streetAddress,
        addressLocality: company.city,
        addressRegion: company.region,
        postalCode: company.postalCode,
        addressCountry: 'IN',
      },
      areaServed: 'IN',
      contactPoint: {
        '@type': 'ContactPoint',
        contactType: 'sales',
        email: company.email,
        telephone: company.phoneE164,
        areaServed: 'IN',
        availableLanguage: 'English',
      },
      sameAs: socials.map((social) => social.href),
    },
    {
      '@type': 'WebSite',
      '@id': WEBSITE_ID,
      url: SITE_URL,
      name: SITE_NAME,
      inLanguage: 'en-IN',
      publisher: { '@id': ORGANIZATION_ID },
    },
  ],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    // suppressHydrationWarning: the inline script below adds the `js` class before React hydrates.
    <html lang="en-IN" className={`${sans.variable} ${accent.variable} ${mono.variable}`} suppressHydrationWarning>
      <head>
        {/* Marks JavaScript as available so scroll-reveal starting states apply; no-JS visitors see everything. */}
        <script dangerouslySetInnerHTML={{ __html: "document.documentElement.classList.add('js')" }} />
      </head>
      <body>
        <a className="skip" href="#main">
          Skip to content
        </a>
        <Masthead />
        <main id="main">{children}</main>
        <SiteFoot />
        <WhatsAppWidget />
        <QuotePopupLoader />
        <ScrollEffects />
        <JsonLd data={organizationSchema} />
      </body>
    </html>
  );
}
