// Real CanzoTech photographs (web copies generated by scripts/optimize-images.mjs from source-files/).
// Width/height are the files' real pixel sizes so next/image reserves space and nothing shifts.

export type Photo = { src: string; width: number; height: number; alt: string };

export const photos = {
  officeFloor: {
    src: '/images/team/office-floor.webp',
    width: 760,
    height: 410,
    alt: 'The CanzoTech office floor, with engineers working at long rows of desks',
  },
  teamCollaboration: {
    src: '/images/team/team-collaboration.webp',
    width: 712,
    height: 421,
    alt: 'CanzoTech designers and engineers gathered around a table, reviewing printed designs together',
  },
  careersTeam: {
    src: '/images/team/careers-team.webp',
    width: 695,
    height: 620,
    alt: 'CanzoTech colleagues discussing work on a laptop in the office',
  },
  planningWall: {
    src: '/images/team/planning-wall.webp',
    width: 479,
    height: 335,
    alt: 'A CanzoTech team member walking two colleagues through a project planning board',
  },
  conferenceRoom: {
    src: '/images/team/conference-room.webp',
    width: 1000,
    height: 440,
    alt: 'A CanzoTech team member presenting at a whiteboard to colleagues in a conference room',
  },
} satisfies Record<string, Photo>;
