import type { Metadata } from 'next';
import { company } from './site-data';

// Production origin. Canonicals, Open Graph URLs, the sitemap and structured data all derive from this.
export const SITE_URL = 'https://www.canzotech.com';
export const SITE_NAME = company.name;
export const SITE_LOCALE = 'en_IN';
export const ORGANIZATION_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;
/** Generated by app/opengraph-image.tsx. */
const DEFAULT_OG_IMAGE = '/opengraph-image';

export function absoluteUrl(path = '/') {
  return new URL(path, SITE_URL).toString();
}

type PageMeta = {
  /** Page title without the brand; the root layout appends " — CanzoTech". */
  title: string;
  description: string;
  /** Site-relative path, e.g. "/services". Becomes the canonical and og:url. */
  path: string;
  /** Share-card image path; defaults to the site-wide card from app/opengraph-image.tsx. */
  image?: string;
  /** Keep the page out of search results while still letting crawlers follow its links. */
  noIndex?: boolean;
};

/**
 * Builds a page's metadata so every route gets its own canonical, Open Graph and Twitter tags.
 * Without this, pages silently inherit the homepage's og:title and og:description from the root layout.
 */
export function pageMetadata({ title, description, path, image = DEFAULT_OG_IMAGE, noIndex = false }: PageMeta): Metadata {
  const socialTitle = `${title} — ${SITE_NAME}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      locale: SITE_LOCALE,
      url: path,
      title: socialTitle,
      description,
      // Setting openGraph replaces the inherited object and any opengraph-image file, so the image is always explicit.
      images: [{ url: image, width: 1200, height: 630, alt: socialTitle }],
    },
    twitter: { card: 'summary_large_image', title: socialTitle, description },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}

export type Crumb = { label: string; href?: string };

/** schema.org BreadcrumbList. The current page (last crumb) may omit its URL, which Google accepts. */
export function breadcrumbSchema(crumbs: Crumb[]) {
  const trail: Crumb[] = [{ label: 'Home', href: '/' }, ...crumbs];
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.label,
      ...(crumb.href ? { item: absoluteUrl(crumb.href) } : {}),
    })),
  };
}
